packages:
  - apps/cli
  - apps/frontend
  - packages/*
sharedWorkspaceLockfile: false
allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@sentry/cli': true
  esbuild: true
  vue-demi: true
catalog:
  '@types/hast': 3.0.5
  '@types/mdast': 4.0.4
  isomorphic-dompurify: 3.22.0
  lru-cache: 11.5.2
  rehype-stringify: 10.0.1
  remark-gfm: 4.0.1
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  unified: 11.0.5
  unist-util-visit: 5.1.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
minimumReleaseAgeExclude:
  - '@koyori-app/openapi-vue-query'
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
saveExact: true
catalogMode: prefer
